onlineshop/urls.py
from django.urls import path
from . import views
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView


urlpatterns = [
    path('', views.show_home, name='show_home'),
    path('community/', views.about, name='community'),
    path('clothes/', PostListView.as_view(), name='clothes'),
    path('post/new', PostCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    ]

onlinestore/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('onlineshop.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('profile_update/', user_views.profile_update, name='profile-update'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', user_views.custom_logout_view, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlineshop/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})


class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='post_images/')

    def __str__(self):
        return f'{self.post.title} Image'

onlineshop/forms.py
from django import forms
from .models import Post, PostImage


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']


class PostImageForm(forms.ModelForm):
    class Meta:
        model = PostImage
        fields = ['image']


PostImageFormSet = forms.inlineformset_factory(Post, PostImage, form=PostImageForm, extra=3)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

onlineshop/views.py
from django.utils import timezone
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post, PostImage
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import PostForm, PostImageFormSet


def show_home(request):
    return render(request, 'onlineshop/home.html')


def about(request):
    return render(request, 'onlineshop/community.html')


class PostListView(ListView):
    model = Post
    template_name = 'onlineshop/clothes.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']


class PostDetailView(DetailView):
    model = Post
    template_name = 'onlineshop/post_detail.html'


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['images'] = PostImageFormSet(self.request.POST, self.request.FILES)
        else:
            data['images'] = PostImageFormSet()
        return data

    def form_valid(self, form):
        form.instance.author = self.request.user
        context = self.get_context_data()
        images = context['images']
        self.object = form.save()
        if images.is_valid():
            images.instance = self.object
            images.save()
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['images'] = PostImageFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            data['images'] = PostImageFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        form.instance.author = self.request.user
        context = self.get_context_data()
        images = context['images']
        self.object = form.save()
        if images.is_valid():
            images.instance = self.object
            images.save()
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

onlineshop/templates/onlineshop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/clothes.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
</head>
<body>
    <header>
       <li><a href="{% url 'show_home' %}" class="auth-links" style="font-size: 1.7em; background: #1c0522;
    box-shadow: 0 0 5px lawngreen,
                0 0 25px #03e9f4,
                0 0 50px #8803f4,
                0 0 200px #03e9f4; color: lightpink; font-family: 'Baloo Tammudu 2' ">ホームページ</a></li>
        <ul>
         {% if user.is_authenticated %}
            <li><a href="{% url 'clothes' %}" class="auth-links">Clothes</a></li>
            <li><a href="{% url 'profile' %}" class="auth-links">My Profile</a></li>
            <li><a href="{% url 'post_new' %}" class="auth-links">Create Post</a></li>
            <li><a href="{% url 'logout' %}" class="auth-links">Logout</a></li>
        {% else %}
            <li><a href="{% url 'login' %}" class="auth-links">Login</a></li>
            <li><a href="{% url 'register' %}" class="auth-links">Register</a></li>
        {% endif %}
        </ul>
    </header>
    <main role="main" class="container">
      <div class="row">
          <div class="col-md-8">
              {%  if messages%}
                {% for message in messages %}
                    <div class="alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
              {% endif %}
          </div>
        <div class="col-md-8">
           {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-sectionw"></div>
              </div>

        <footer style="margin-left: 400px" class="">
          <ul class="nav justify-content-center border-bottom"  style="margin-top: 200%">
            <li class="nav-item"><a href="{% url 'show_home' %}" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
          </ul>
          <p class="text-center text-muted">&copy; Masha's Demo Project 2024</p>
        </footer>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

onlineshop/templates/onlineshop/clothes.html
{% extends 'onlineshop/base.html' %}

{% block content %}

<h1 style="color: white; margin-top: 50px; margin-left: 180px"><b style="font-family: 'Academy Engraved LET' ">Swipe Clothes Here</b></h1>
<hr>
{% for post in posts %}
    <article class="media content-section">
        <img style="image-resolution: 300dpi;width: 117px; height: 118px; border: 5px solid deeppink" class="circle" src="{{ post.author.profile.image.url }}">
        <div class="media-body">
            <div class="article-metadata>">
                <a class="mr-2" href="#">{{ post.author }}</a>
                <small class="text-muted">{{ post.date_posted }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post_detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
        <br>
    </article>

{% endfor %}
{% endblock content %}

onlineshop/templates/onlineshop/community.html
{% extends 'onlineshop/base.html' %}
{% block content %}
    <div class="container" style="font-family: 'Brush Script MT'; color: white; padding: 20px; margin-top: 10px">
    <h1>Our Community</h1>
    </div>
{% endblock content %}

onlineshop/templates/onlineshop/home.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Exchange Clothing</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
        <a href="#" class="logo"></a>
        <ul>
            <li><a href="#" class="active" class="auth-links">Home</a></li>
            <li><a href="{% url 'clothes' %}" class="auth-links">Clothes</a></li>
            <li><a href="#" class="auth-links">Events</a></li>
            <li><a href="#" class="auth-links">Community</a></li>
        </ul>
    </header>
    <section>
        <img src="{% static 'img/stars.png' %}" id="stars">
        <img src="{% static 'img/hanger.png' %}" id="hanger">
        <img src="{% static 'img/back.png' %}" id="back">
        <h2 id="text">Wardrobe Wonders</h2>
        <a href="{% url 'clothes' %}" id="btn">Explore</a>
        <img src="{% static 'img/front.png' %}" id="front">
    </section>
    <div id="sec" class="sec">
        <h2 style="font-family: 'Academy Engraved LET'">Clothes Exchange Website</h2><br><br>
        <p>In a bustling town nestled between rolling hills and vibrant cityscapes,
            there was a unique community that thrived on the spirit of sharing and sustainability.
            This was not an ordinary place; it was a haven where fashion met philanthropy, and every
            garment had a story to tell. Welcome to the world of Wardrobe Wonders, the ultimate clothes
            exchange community that has transformed the way people think about fashion and consumption.<br><br>
            <b>The Beginning</b><br><br>
            The genesis of Wardrobe Wonders began with a simple yet profound idea. A group of friends,
            disillusioned by the fast fashion industry and the environmental toll it was taking, decided to
            take a stand. Masha, the visionary behind the community, was an environmental science graduate
            with a passion for fashion. She saw the potential in creating a platform where people could
            exchange clothes, reducing waste and fostering a sense of community.<br><br>

            "Why buy new when you can exchange?" Masha would often say. Her words resonated with many, and soon, a small
            group of like-minded individuals began meeting in her cozy living room. They brought clothes they
            no longer wore, shared stories behind each item, and swapped garments with each other. What
            started as a modest gathering soon evolved into a movement.<br><br>

            <b>Growing Pains and Innovations</b><br><br>
            As the word spread, more people wanted to join the clothes exchange. Masha and her friends realized they
            needed a larger space and a more structured approach. They rented a small storefront in the heart of the
            town, transforming it into a vibrant exchange hub. The walls were adorned with racks of clothes, neatly
            categorized by size, season, and style. A corner was dedicated to accessories, another to shoes, and a
            cozy nook with a vintage mirror where members could try on their finds.<br><br>

            To manage the growing inventory and keep things organized, Masha developed a simple yet effective system.
            Members would bring in their gently used clothes and receive points based on the quality and type of garments.
            These points could then be used to "purchase" other items from the exchange. This system not only ensured
            fairness but also encouraged people to bring in high-quality items.<br><br>

            <b>Stories Behind the Clothes</b><br><br>
            One of the most enchanting aspects of Wardrobe Wonders was the stories behind each piece of clothing.
            Every garment had a tag where the previous owner could write a brief note about its history. There were dresses
            worn to weddings, coats that had traveled across continents, and scarves knitted by grandmothers. These stories
            added a layer of depth and connection, making each exchange more meaningful.<br><br>

            Take, for example, the story of Lily's red dress. Lily was a young woman who had worn the dress to her first job
            interview. It was a symbol of her determination and dreams. When she donated it to Wardrobe Wonders, she wrote a
            heartfelt note hoping that the next person who wore it would feel just as confident and empowered. The dress found its
            way to Tatiana, a recent immigrant who wore it to her citizenship ceremony. The red dress, now imbued with new memories,
            continued its journey, inspiring everyone who came across it.<br><br>

            <b>Building a Sustainable Future</b><br><br>
            Wardrobe Wonders was more than just a clothes exchange; it was a movement toward a sustainable future. Masha and her
            team organized workshops and events to educate the community about the environmental impact of fast fashion. They invited
            local artisans to teach mending and upcycling techniques, encouraging people to extend the life of their clothes.
            The community also partnered with local charities and shelters, donating surplus clothes to those in need. This not only
            helped the less fortunate but also reinforced the values of sharing and caring that Wardrobe Wonders stood for.<br><br>

            <b>Inspiring Change Beyond the Community</b><br><br>
            The success of Wardrobe Wonders caught the attention of neighboring towns and cities. Masha began receiving invitations to speak
            at schools, community centers, and even corporate events. She shared the story of Wardrobe Wonders, emphasizing the power of grassroots
            movements in driving change.<br><br>

            Inspired by her talks, many communities started their own clothes exchange initiatives. Wardrobe Wonders became a blueprint for sustainable
            fashion practices, proving that small actions could lead to significant impact. Masha's vision was coming to life, one exchanged garment at a time.<br><br>

            <b>Personal Journeys and Transformations</b><br><br>
            The magic of Wardrobe Wonders lay not only in the clothes but also in the personal journeys it facilitated. Members often shared how the community had
            transformed their lives. For many, it was about finding unique, affordable fashion without the guilt of contributing to environmental degradation. For others,
            it was about the connections and friendships they had formed.<br><br>

            Sophie, a single mother, found solace and support in the community. She had always loved fashion but could never afford the latest trends. Through Wardrobe Wonders, she
            not only discovered beautiful clothes but also met other mothers who shared her struggles and triumphs. Together, they formed a support network, helping each other through
            life's ups and downs.<br><br>

            For Jason, a recent college graduate, the clothes exchange was a lifeline. Struggling to make ends meet while starting his career, he found confidence in the professional attire he
            acquired from Wardrobe Wonders. Each suit and tie he wore carried the hope and success stories of their previous owners, motivating him to pursue his dreams. <br><br>

            <b>Celebrating Milestones</b><br><br>
            Wardrobe Wonders celebrated several milestones along its journey. Each year, they hosted an anniversary gala, inviting members to share their stories and showcase their favorite
            exchanged outfits. The event was a celebration of community, sustainability, and fashion. Local bands performed, artisans displayed their crafts, and the atmosphere was filled with
            joy and camaraderie.<br><br>

            The 5th anniversary was particularly special. Masha and her team had worked tirelessly to expand their reach and impact. They launched an online platform, allowing people from different
            parts of the country to participate in the clothes exchange. The online community grew rapidly, connecting people who shared a passion for sustainable fashion.<br><br>

            <b>The Future of Wardrobe Wonders</b><br><br>
            Looking ahead, Wardrobe Wonders aims to continue its mission of promoting sustainable fashion and fostering community connections. Masha envisions a world where clothes exchanges
            are as common as traditional retail stores, where people think twice before discarding a garment and consider its potential new life with someone else.<br><br>

            The team is working on expanding their educational programs, reaching out to schools to teach children about the importance of sustainability from a young age. They are
            also exploring partnerships with fashion designers to create exclusive upcycled collections, blending creativity with environmental responsibility.<br><br>

            Wardrobe Wonders is not just about exchanging clothes; it's about exchanging values, stories, and dreams. It's about creating a world where fashion is a force for good,
            where every garment is cherished, and where communities come together to build a sustainable future.<br><br>
</p>
    </div>
    <script>
        let stars = document.getElementById('stars');
        let hanger = document.getElementById('hanger');
        let back = document.getElementById('back');
        let text = document.getElementById('text');
        let btn = document.getElementById('btn');
        let front = document.getElementById('front');

        window.addEventListener('scroll', function (){
            let value = window.scrollY;
            stars.style.left = value * 0.25 + 'px';
            hanger.style.right = value * 0.50 +"px";
            back.style.top = value * 0.50 + 'px';
            text.style.marginRight = value * 4 + 'px';
            text.style.marginTop = value * 1.5 + 'px';
            btn.style.marginTop = value * 1.5 + 'px';
        })
    </script>
</body>
</html>

onlineshop/templates/onlineshop/post_confirm_delete.html
{% extends 'onlineshop/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="content-section">
        <form action="" method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend claass="border-bottom mb-4">Delete Posts</legend>
            <h4>Hey, do you want to delete this post <b>"{{ object.title }}"</b></h4>
            </fieldset>
            <div class="form-group">
                <button type="submit">Delete</button>
            </div>
        </form>
    </div>
{% endblock content %}

onlineshop/templates/onlineshop/post_detail.html
{% extends 'onlineshop/base.html' %}

{% block content %}
<hr>
<article class="media content-section">
    <img style="width: 200px; height: 210px; border: 5px solid deeppink" class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#" style="font-size: large">{{ object.author }}</a>
            <small class="text-muted">{{ object.date_posted }}</small>
        </div>
        <h2><a class="article-title" href="#">{{ object.title }}</a></h2>
        <p class="article-content">{{ object.content }}</p>

        {% if object.author == user %}
        <div class="mt-3">
            <a class="btn btn-outline-success" href="{% url 'post_update' object.id %}">Update</a>
            <a class="btn btn-outline-danger" href="{% url 'post_delete' object.id %}">Delete</a>
        </div>
        {% endif %}
    </div>
    <br>
</article>

<!-- Card Hover Effect for Images -->
<div class="post-images mt-4">
    <div class="row">
        {% for image in object.images.all %}
        <div class="col-md-4 mb-4">
            <div class="image-card">
                <img src="{{ image.image.url }}" alt="Image for {{ object.title }}" onclick="openModal('{{ image.image.url }}')">
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<!-- Image Modal -->
<div id="imageModal" class="image-modal">
    <span class="close" onclick="closeModal()">&times;</span>
    <img class="image-modal-content" id="modalImage">
</div>

<style>
.image-card {
    position: relative;
    overflow: hidden;
    cursor: pointer;
    transition: transform 0.3s ease-in-out;
    border: 1px solid #ddd;
    border-radius: 10px;
}

.image-card img {
    width: 100%;
    height: auto;
    display: block;
    transition: transform 0.3s ease-in-out;
}

.image-card:hover img {
    transform: scale(1.1);
}

/* Modal Styles */
.image-modal {
    display: none;
    position: fixed;
    z-index: 1000;
    padding-top: 60px;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: rgb(0,0,0);
    background-color: rgba(0,0,0,0.9);
}

.image-modal-content {
    margin: auto;
    display: block;
    width: 80%;
    max-width: 700px;
}

.image-modal-content, .close {
    animation-name: zoom;
    animation-duration: 0.6s;
}

@keyframes zoom {
    from {transform: scale(0)}
    to {transform: scale(1)}
}

.close {
    position: absolute;
    top: 15px;
    right: 35px;
    color: #fff;
    font-size: 40px;
    font-weight: bold;
    transition: 0.3s;
}

.close:hover,
.close:focus {
    color: #bbb;
    text-decoration: none;
    cursor: pointer;
}
</style>

<script>
function openModal(src) {
    document.getElementById('imageModal').style.display = 'block';
    document.getElementById('modalImage').src = src;
}

function closeModal() {
    document.getElementById('imageModal').style.display = 'none';
}
</script>

{% endblock content %}

onlineshop/templates/onlineshop/post_form.html
{% extends 'onlineshop/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
              <fieldset class="form-group">
                <legend class="border-bottom mb-4">New Post</legend>
                {{ form|crispy }}
                {{ images.management_form }}
                {% for form in images %}
                {{ form|crispy }}
                {% endfor %}
                </fieldset>

            <div class="form-group">
                <button class="btn btn-primary" style="margin-top: 10px" type="submit">Save</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/login.html
{% extends 'onlineshop/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form action="" method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Welcome Back!</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="auth-links" type="submit">Sign In</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">Haven't signed up yet? <a href="{% url 'register' %}">Register</a></small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends 'onlineshop/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="content-section">
    <h2>Are you sure you want to log out?</h2>
    <form id="logout-form" action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="auth-links" type="submit">Logout</button>
            </div>
        </form>
</div>

{% endblock content %}

users/templates/users/profile.html
{% extends 'onlineshop/base.html' %}
{% block content %}
{% load crispy_forms_tags %}


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <div class="cardd">

      <div class="m-b-25">
          <img class="rounded-circle account-img"  id="profile-img" src="{{ user.profile.image.url }}"  alt="User-Profile-Image">
      </div>
      <h1 id="profile-h1">{{ user.username|title }}</h1>
      <p class="title">{{ user.email }}</p>
      <!-- <p>My Social Live  Below</p> -->
      <a href="#" id="auth-links"><i class="fa fa-dribbble"></i></a>
      <a href="#" id="auth-links"><i class="fa fa-twitter"></i></a>
      <a href="#" id="auth-links"><i class="fa fa-linkedin"></i></a>
      <a href="#" id="auth-links"><i class="fa fa-facebook"></i></a>

      <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              {{ u_form|crispy }}
              {{ p_form|crispy }}
          </fieldset>
      </form>

      <p>
          <button style="height: 80px"><a href="{% url 'profile-update' %}" class="auth-links">
              Update Profile</a>
          </button>
      </p>
    </div>
{% endblock content %}

users/templates/users/profile_update.html
{% extends 'onlineshop/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Update Profile</legend>
            {{ u_form|crispy }}
<!--            {{ p_form|crispy }}-->
            <div class="custom-file mb-3">
                <input type="file" name="{{ p_form.image.name }}" class="custom-file-input" id="id_image">
                <label class="custom-file-label" for="id_image">Upload New Picture</label>
            </div>
            <div class="form-group">
                <img id="image_preview" src="{% if p_form.instance.image %}{{ p_form.instance.image.url }}{% endif %}"
                     alt="Image Preview"
                     style="max-width: 100%; height: auto; display: {% if p_form.instance.image %}block{% else %}none{% endif %};"/>
            </div>
        </fieldset>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </form>
    <script>
        document.getElementById('id_image').addEventListener('change', function (event) {
            var file = event.target.files[0];
            var reader = new FileReader();

            reader.onload = function (e) {
                var img = document.getElementById('image_preview');
                img.src = e.target.result;
                img.style.display = 'block';
            };

            reader.readAsDataURL(file);
        });
    </script>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends 'onlineshop/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form action="" method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create A New Account</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">Already have an account? <a href="">Login</a></small>
        </div>
    </div>
{% endblock content %}